-- Accounts Supabase project only.
--
-- This file is intentionally outside supabase/migrations/, which belongs to
-- the catalogue/data Supabase project. Apply it only after reviewing the
-- dedicated Accounts project and its existing auth schema.

create table if not exists public.subscription_entitlements (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references auth.users(id) on delete cascade,
  entitlement_key text not null check (btrim(entitlement_key) <> ''),
  status text not null check (status in ('active', 'grace_period', 'billing_retry', 'expired', 'revoked')),
  provider text not null check (btrim(provider) <> ''),
  product_id text not null check (btrim(product_id) <> ''),
  provider_transaction_id text,
  original_transaction_id text,
  provider_signed_at timestamptz,
  expires_at timestamptz,
  verified_at timestamptz not null default now(),
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint subscription_entitlements_identity_key
    unique (account_id, entitlement_key, provider, product_id)
);

create index if not exists subscription_entitlements_account_key_idx
  on public.subscription_entitlements (account_id, entitlement_key);

create table if not exists public.subscription_events (
  id bigint generated by default as identity primary key,
  provider text not null check (btrim(provider) <> ''),
  provider_event_id text not null check (btrim(provider_event_id) <> ''),
  event_type text not null check (btrim(event_type) <> ''),
  provider_transaction_id text,
  original_transaction_id text,
  payload jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  processing_error text,
  constraint subscription_events_provider_event_key
    unique (provider, provider_event_id)
);

create index if not exists subscription_events_original_transaction_idx
  on public.subscription_events (provider, original_transaction_id)
  where original_transaction_id is not null;

alter table public.subscription_entitlements enable row level security;
alter table public.subscription_events enable row level security;

-- The browser may read its own verified entitlements, but cannot create,
-- change, revoke, or delete them. Only the trusted server/webhook processor
-- should write subscription state.
revoke all on table public.subscription_entitlements from public, anon, authenticated;
grant select on table public.subscription_entitlements to authenticated;
grant all on table public.subscription_entitlements to service_role;

create policy subscription_entitlements_select_own
  on public.subscription_entitlements
  for select
  to authenticated
  using ((select auth.uid()) = account_id);

-- The event log is server-only. RLS remains enabled as defense in depth even
-- though the exposed roles receive no table privileges.
revoke all on table public.subscription_events from public, anon, authenticated;
grant all on table public.subscription_events to service_role;

grant usage, select on sequence public.subscription_events_id_seq to service_role;

notify pgrst, 'reload schema';
